baseurl = "http://sciphy.netlify.com"
languageCode = "en"
title = "Science and Physiotherapy"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/jnshsrs\">Jens Hüsers</a> 2018"
disqusShortname = "shortname"
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true
math = true

[params]
    summary_length = 300

[params.assets]
customCSS = ["css/custom.css"]

[params.rss]

includeContent = true # Includes whole content in rss
authorName = "Jens Hüsers" # Site author's full name
authorEmail = "jenshuesers@gmail.com"

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "jnshsrs" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "jnshsrs"
github = "jnshsrs"
email = "jenshuesers@gmail.com"
linkedin = "Jens Hüsers"
instagram = ""
codepen = ""

[params.matomoAnalytics]
siteID = 1
rootURL = "//matomo.example.com/"

[params.fathomAnalytics]
rootURL = "//fathom.example.com/"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

